### ISSUE TITLE
AttributeError raised when trying to estimate a pose

### ISSUE THREAD

**Issue by mohamedamjad** [pento-group/terran#13]
The code:

```
from terran.pose import pose_estimation
from terran.io import open_image
from terran.vis import vis_poses
from terran.vis import display_image

image = open_image('usainbolt2.jpg')
display_image(vis_poses(image, pose_estimation(image)))
```

The Error:

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    display_image(vis_poses(image, pose_estimation(image)))
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.7/lib/python3.7/site-packages/terran/pose/__init__.py", line 218, in __call__
    out = self.model.call(images)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.7/lib/python3.7/site-packages/terran/pose/openpose/wrapper.py", line 477, in call
    get_keypoints(peaks_by_id, humans, scale=scale)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.7/lib/python3.7/site-packages/terran/pose/openpose/wrapper.py", line 73, in get_keypoints
    y = (y.cpu().numpy() / scale).astype(np.int32)
AttributeError: 'numpy.float64' object has no attribute 'cpu'
```

**Comment by leopiney** [comment]
Hey @mohamedamjad Thanks for submitting the issue! We'll let you know when the release is ready 👍
